export default function Dashboard() {
  return (
    <main className="absolute z-1 h-screen w-screen overflow-auto">
      <h1>DASHBOARD</h1>
      <h1>DASHBOARD</h1>
      <h1>DASHBOARD</h1>
      <h1>DASHBOARD</h1>
      <h1>DASHBOARD</h1>
      <h1>DASHBOARD</h1>
      <h1>DASHBOARD</h1>
      <h1>DASHBOARD</h1>
      <h1>DASHBOARD</h1>
      <h1>DASHBOARD</h1>
      <h1>DASHBOARD</h1>
      <h1>DASHBOARD</h1>
      <h1>DASHBOARD</h1>
      <h1>DASHBOARD</h1>
      <h1>DASHBOARD</h1>
      <h1>DASHBOARD</h1>
      <h1>DASHBOARD</h1>
      <h1>DASHBOARD</h1>
      <h1>DASHBOARD</h1>
      <h1>DASHBOARD</h1>
      <h1>DASHBOARD</h1>
      <h1>DASHBOARD</h1>
      <h1>DASHBOARD</h1>
      <h1>DASHBOARD</h1>
      <h1>DASHBOARD</h1>
      <h1>DASHBOARD</h1>
      <h1>DASHBOARD</h1>
      <h1>DASHBOARD</h1>
      <h1>DASHBOARD</h1>
      <h1>DASHBOARD</h1>
      <h1>DASHBOARD</h1>
      <h1>DASHBOARD</h1>
      <h1>DASHBOARD</h1>
      <h1>DASHBOARD</h1>
      <h1>DASHBOARD</h1>
      <h1>DASHBOARD</h1>
      <h1>DASHBOARD</h1>
      <h1>DASHBOARD</h1>
      <h1>DASHBOARD</h1>
      <h1>DASHBOARD</h1>
      <h1>DASHBOARD</h1>
      <h1>DASHBOARD</h1>
      <h1>DASHBOARD</h1>
      <h1>DASHBOARD</h1>
      <h1>DASHBOARD</h1>
      <h1>DASHBOARD</h1>
      <h1>DASHBOARD</h1>
      <h1>DASHBOARD</h1>
      <h1>DASHBOARD</h1>
      <h1>DASHBOARD</h1>
      <h1>DASHBOARD</h1>
      <h1>DASHBOARD</h1>
      <h1>DASHBOARD</h1>
      <h1>DASHBOARD</h1>
    </main>
  );
}
